# Generated by Django 4.2.2 on 2023-06-21 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_description_transaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingticket',
            name='recipients_hash',
        ),
    ]
