# Generated by Django 4.2.2 on 2023-06-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_pendingticket_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='wager',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='What user stakes for a task', max_digits=16),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_id',
            field=models.CharField(help_text='Card ID', max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('diamond', 'Diamond'), ('club', 'Club')], default='diamond', max_length=25),
        ),
    ]
